# -*- coding: utf-8 -*-
"""Cv and TFIDF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y2_5KOrSydeBE6rmTuGhvaWkaRMGRoza

# [Code Reference - Count Vectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)
"""

from sklearn.feature_extraction.text import CountVectorizer

# there are 4 documents in corpua
corpus = [
          'This is the first document.',
          'This document is the second document.',
          'And this is the third one.',
          'Is this the first document?',
          ]

          
vectorizer = CountVectorizer() # creating instance of Count Vectorizer
''' Each Word is Seperated as tokens, number of time each token occurs in a document is counted in a count Vectorizer'''


X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

from pandas import DataFrame
print(DataFrame(X.toarray(),columns = vectorizer.get_feature_names()))

"""# [Code Reference - TF-IDF](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)


## TF = Number of repetation of words in a sentence / Number of words in a sentence

## IDF = log( Number of sentences / Number of sentences containing the word)

# TF-IDF = Term Frequency (TF) * Inverse Document Frequency (IDF)
"""

from sklearn.feature_extraction.text import TfidfVectorizer
# there are 4 documents in corpua
corpus = [
          'This is the first document.',
          'This document is the second document.',
          'And this is the third one.',
          'Is this the first document?',
          ]


vectorizer = TfidfVectorizer() # creating instance of TF-IDF


X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

from pandas import DataFrame
print(DataFrame(X.toarray(),columns = vectorizer.get_feature_names()))

print(X.shape)

